# Generated by Django 4.1.2 on 2026-09-30 18:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150)),
                ('mobile', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=1050)),
                ('status', models.PositiveSmallIntegerField(default=1)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserECCKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_key_pem', models.TextField(help_text='PEM-encoded SECP256R1 public key.')),
                ('private_key_pem', models.TextField(blank=True, help_text='PEM-encoded SECP256R1 private key (no passphrase).', null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ecc_key', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file_password', models.CharField(blank=True, max_length=100, null=True)),
                ('file_path', models.FileField(blank=True, null=True, upload_to='upload/', verbose_name='Upload File')),
                ('encrypted_data', models.BinaryField(blank=True, null=True)),
                ('status', models.PositiveSmallIntegerField(default=1)),
                ('file_name_with_ext', models.CharField(blank=True, max_length=255, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('sensitivity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', help_text='Auto-classified sensitivity level based on file type.', max_length=10)),
                ('nonce', models.BinaryField(blank=True, null=True)),
                ('cipher_used', models.CharField(default='AES-128-ECB', max_length=20)),
                ('require_step_up', models.BooleanField(default=False)),
                ('wrapped_dek', models.BinaryField(blank=True, null=True)),
                ('wrap_nonce', models.BinaryField(blank=True, null=True)),
                ('ephemeral_public_key', models.TextField(blank=True, null=True)),
                ('file_password_hash', models.CharField(blank=True, max_length=128, null=True)),
                ('file_size_bytes', models.PositiveIntegerField(blank=True, help_text='Plaintext file size in bytes (recorded at upload time).', null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('security_question', models.CharField(blank=True, help_text='Security question used for step-up verification.', max_length=255, null=True)),
                ('security_answer_hash', models.CharField(blank=True, help_text='Salted password hash of the security answer.', max_length=128, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=20, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(blank=True, max_length=200, null=True)),
                ('state', models.CharField(blank=True, max_length=200, null=True)),
                ('pin', models.CharField(blank=True, max_length=10, null=True)),
                ('country', models.CharField(blank=True, max_length=200, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FileTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remarks', models.CharField(max_length=250)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('file_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cloudstorage.uploadfile')),
                ('receiver_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_receiver_user', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_sender_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=250)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('receiver_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_receiver_user', to=settings.AUTH_USER_MODEL)),
                ('sender_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sender_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AnomalyEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_username', models.CharField(blank=True, max_length=150, null=True)),
                ('event_type', models.CharField(choices=[('login_success', 'Login Success'), ('login_failed', 'Login Failed'), ('logout', 'Logout'), ('upload', 'Upload'), ('download', 'Download'), ('transfer', 'Transfer'), ('profile_update', 'Profile Update'), ('chat', 'Chat'), ('system', 'System')], max_length=30)),
                ('source_ip', models.CharField(blank=True, max_length=50, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500, null=True)),
                ('risk_score', models.FloatField(default=0.0)),
                ('anomaly_score', models.FloatField(default=0.0)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=20)),
                ('recommended_action', models.CharField(default='monitor', max_length=50)),
                ('action_taken', models.CharField(default='monitor', max_length=50)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ActivityLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_log', models.CharField(choices=[('Login', 'Login'), ('Logout', 'Logout'), ('FileUpload', 'FileUpload'), ('DeleteFile', 'DeleteFile'), ('FileTransfer', 'FileTransfer'), ('UpdateProfile', 'UpdateProfile'), ('ChangePassword', 'ChangePassword'), ('SendChat', 'SendChat'), ('DeleteChat', 'DeleteChat')], max_length=50)),
                ('ip_address', models.CharField(blank=True, max_length=50, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('event_context', models.JSONField(blank=True, default=dict)),
                ('anomaly_score', models.FloatField(blank=True, null=True)),
                ('anomaly_severity', models.CharField(blank=True, max_length=20, null=True)),
                ('anomaly_action', models.CharField(blank=True, max_length=50, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_log_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
